/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DeleteUIArgs } from "./DeleteUIArgs";
import { UICountArgs } from "./UICountArgs";
import { UIFindManyArgs } from "./UIFindManyArgs";
import { UIFindUniqueArgs } from "./UIFindUniqueArgs";
import { UI } from "./UI";
import { UIService } from "../ui.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => UI)
export class UIResolverBase {
  constructor(
    protected readonly service: UIService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "UI",
    action: "read",
    possession: "any",
  })
  async _uisMeta(@graphql.Args() args: UICountArgs): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [UI])
  @nestAccessControl.UseRoles({
    resource: "UI",
    action: "read",
    possession: "any",
  })
  async uis(@graphql.Args() args: UIFindManyArgs): Promise<UI[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => UI, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "UI",
    action: "read",
    possession: "own",
  })
  async ui(@graphql.Args() args: UIFindUniqueArgs): Promise<UI | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => UI)
  @nestAccessControl.UseRoles({
    resource: "UI",
    action: "delete",
    possession: "any",
  })
  async deleteUI(@graphql.Args() args: DeleteUIArgs): Promise<UI | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
